age: 18
pageSize: 20

spring:
  messages:
    basename: message
  application:
    name: assignment
  datasource:
    url: jdbc:mysql://${DB_ENDPOINT}:3306/db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update


